name: Build Binance Trader

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Install .NET Framework 4.8 SDK
        run: choco install dotnetfx --version=4.8.0.20190930 -y

      - name: Restore NuGet packages
        run: nuget restore "Binance Trader.sln"

      - name: Build solution
        run: |
          msbuild "Binance Trader.sln" /p:Configuration=Release /p:Platform=x64 /p:RestorePackages=false /verbosity:minimal

      - name: Archive build output
        run: |
          $buildPath = "BinanceTrader\bin\Release\x64"
          $artifactName = "binance-trader-Release-x64.zip"
          Compress-Archive -Path "$buildPath\*" -DestinationPath "$artifactName" -Force

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: binance-trader-Release-x64
          path: binance-trader-Release-x64.zip
          retention-days: 30 